### ISSUE TITLE
Error: Cannot pipe. Not readable.

### ISSUE THREAD

**Issue by DoubleU23** [andrewrk/node-stream-counter#2]
Any ideas?

```
var   fs = require('fs'),
    childProcess = require('child_process');

var StreamCounter = require('stream-counter');
var counter = new StreamCounter();
var writeStream = fs.createWriteStream(newUrl, "utf8").pipe(counter);
```

```
Module build failed: Error: Cannot pipe. Not readable.
    at WriteStream.Writable.pipe (_stream_writable.js:154:22)
    at Object.module.exports (/var/www/htdocs/projects/SSS/web/node_modules/cssobjects-loader/index.js:46:56)
```

**Comment by bdevel** [comment]
Ran into the same issue with Node v5.3.0.

**Comment by lliss** [comment]
I'm also seeing this on node 4.3.1

**Comment by andrewrk** [comment]
This module is 16 lines of code. Node 4 must have changed the stream API.

**Comment by DoubleU23** [comment]
_**outdated**_
